image: python:3.11

stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install --upgrade pip
  - python -m venv venv
  - source venv/bin/activate
  - pip install ruff 
  - pip install mypy 
  - pip install .[dev]
  - pip install types-requests types-PyYAML

lint:

  stage: lint
  script:
    - ruff check .
    - mypy --exclude build/ .
    - codespell
  tags:
  - docker
    
test:
  script:
    - pytest
    
  tags:
  - docker