[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
where = ["src"]
[project.scripts]
mlhess = "mlhess.main:main"

[project]
name = "mlhess"
version = "0.0.1"

description = "A package to train, test and use ML models for nuclear Hessian."
authors = [{name="Gereon Feldmann", email="feldmann@pc.rwth-aachen.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28",
    "pymatgen",
    "ase",
    "joblib",
    "numpy",
    "pandas",
    "scikit_learn==1.8.0",
    "scipy",
    "torch>=1.1.0",
    "cffi",
    "pkgconfig",
    "tomli",
    "tblite==0.6.0",
    "dftd4==4.2.0",
    "tcgm_lib  @ git+https://gitlab.git.nrw/rwth-bannwarthlab/open_tcgm_lib_py.git",
    ]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff==0.16.5",
    "mypy",
    "codespell",
    "types-requests",
    "types-PyYAML",
]
docs = [
    "sphinx",
    "furo",
]

[tool.mypy]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["tcgm-lib.*","sklearn.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--tb=long -s --cov=mlhess --cov-report=term-missing"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[tool.codespell]
# Words to ignore
ignore-words-list  = "activ,itens, activ"
