[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
where = ["src"]
[project.scripts]
mlhess = "mlhess.main:main"

[project]
name = "mlhess"
version = "0.0.1"

description = "A package to train, test and use ML models for nuclear Hessian."
authors = [{name="Gereon Feldmann", email="feldmann@pc.rwth-aachen.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28",
    "pymatgen",
    "ase",
    "joblib",
    "numpy>=1.0,<2.0",
    "pandas",
    "scikit_learn",
    "scipy",
    "torch>=1.1.0",
    "cffi",
    "pkgconfig",
    "tomli",
    "tblite",
    "dftd4",
    #"tcgm_lib @ git@git.rwth-aachen.de:bannwarthlab/tcgm-lib-py.git"
    #"tblite @ git+https://github.com/awvwgk/tblite.git#subdirectory=python"
    ]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
     "requests>=2.28",
    "pymatgen",
    "ase",
    "joblib",
    "numpy>=1.0,<2.0",
    "pandas",
    "scikit_learn",
    "scipy",
    #"torch @ https://download.pytorch.org/whl/cpu/torch-1.1.0-cp38-cp38-linux_x86_64.whl",
    "cffi",
    "pkgconfig",
    "tomli",
    "tblite",
    "dftd4",
    "ruff",
    "mypy",
    "codespell",
    "types-requests",
    "types-PyYAML",
]

[tool.mypy]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["tcgm-lib.*","sklearn.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--tb=long -s --cov=mlhess --cov-report=term-missing"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[tool.codespell]
# Words to ignore
ignore-words-list  = "activ,itens, activ"
