stages:
  - build
  - lint
  - test

build-hessml_image:
  stage: build
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  script:
    - mkdir -p containers
    - if [ ! -e "containers/${CONTAINER_NAME}.sif" ] ; then apptainer build containers/${CONTAINER_NAME}.sif .gitlab/recipes/${CONTAINER_NAME}.def ; fi
    #- apptainer build --force containers/${CONTAINER_NAME}.sif .gitlab/recipes/${CONTAINER_NAME}.def
  tags:
    - shell
  variables:
    CONTAINER_NAME: "hessml_image"

test:
  stage: test
  image: containers/${CONTAINER_NAME}.sif
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  dependencies:
    - build-hessml_image
  variables:
    IMAGE_NAME: ""
    CONTAINER_NAME: "containers/hessml_image.sif"
    APPTAINER_EXEC_ARGS: "" 
  tags:
    - cpu
  script:
    
    - pytest tests/ --cov 
    
  artifacts:
    when: on_failure
    paths:
      - tests/test_results/
    expire_in: 1 week

lint:
  stage: lint
  image: containers/${CONTAINER_NAME}.sif
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  dependencies:
    - build-hessml_image
  variables:
    IMAGE_NAME: ""
    CONTAINER_NAME: "containers/hessml_image.sif"
    APPTAINER_EXEC_ARGS: "" 
  tags:
    - cpu
  script:
    - . /opt/venv/bin/activate
    - which python
    - pip install scipy
    - pip install .[dev]
    - ruff check .
    - mypy --ignore-missing-imports --exclude build/ .
    - codespell src/
    
  artifacts:
    when: on_failure
    paths:
      - tests/test_results/
    expire_in: 1 week
