stages:
  - build
  - lint
  - test

build-hessml_image:
  stage: build
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  script:
    - mkdir -p containers
    - if [ ! -e "containers/${CONTAINER_NAME}.sif" ] ; then apptainer build containers/${CONTAINER_NAME}.sif .gitlab/recipes/${CONTAINER_NAME}.def ; fi
  tags:
    - shell
  variables:
    CONTAINER_NAME: "hessml_image"

test:
  stage: test
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  dependencies:
    - build-hessml_image
  variables:
    IMAGE_NAME: ""
    CONTAINER_NAME: "containers/hessml_image.sif"
    APPTAINER_EXEC_ARGS: "" 
  tags:
    - cpu
  script:
    - which python3.11
    - source opt/venv/bin/activate 
    - which python3.11
    - pip install .[dev]
    - pip install git+https://gitlab+deploy-token-1478:${PRIVATE_DEPLOY_TOKEN}@git.rwth-aachen.de/bannwarthlab/tcgm-lib-py.git  
    - pytest tests/ --cov 
    

  artifacts:
    when: on_failure
    paths:
      - tests/test_results/
    expire_in: 1 week

lint:
  stage: lint
  cache:
    key: "hessml_image-$CI_COMMIT_REF_SLUG"
    paths:
      - containers/
  dependencies:
    - build-hessml_image
  variables:
    IMAGE_NAME: ""
    CONTAINER_NAME: "containers/hessml_image.sif"
    APPTAINER_EXEC_ARGS: "" 
  tags:
    - cpu
  script:
    - source venv/bin/activate
    # Run linters
    - ruff check .
    - mypy --ignore-missing-imports --exclude build/ .
    - codespell src/