threads = 4
runtype = 'hessian'

[feature_generation]
features = 'ml_features.csv'
target = 'hessian'
dipm = 'xyz_dipm.csv'
coord = 'coord.xyz'            
binary = 'calc'
subfolder = 'True'

[training_testing]
random_seed = 42
train_split = 0.75
test_split = 0.25
model_name = 'gdb7_set'
total_geometries = 210
observables = ['ZPE','frequencies']

[[training_testing.homo]]
N_est = 100
N_depth = 30

[[training_testing.hetero]]
n_estimators = 175
max_depth = 30

[predict]


